if &compatible | set nocompatible | endif

let s:init_dir = fnamemodify(expand('<sfile>'), ':h')
let $INIT_DIR = s:init_dir

" dein bootstrap
let s:dein_dir = expand('~/.cache/dein') 
call init#bootstrap(s:dein_dir)

if dein#min#load_state(s:dein_dir)
  let g:dein#inline_vimrcs = [
        \ s:init_dir .. '/init-base.vim',
        \ s:init_dir .. '/init-filetype.vim',
        \ ]

  let s:toml = s:init_dir .. '/dein.toml'
  let s:lazy_toml = s:init_dir .. '/dein-lazy.toml'
  let s:filetype_toml = s:init_dir .. '/dein-filetype.toml'
  call dein#begin(s:dein_dir, expand('<sfile>'))
  call dein#load_toml(s:toml, #{lazy: v:false})
  call dein#load_toml(s:lazy_toml, #{lazy: v:true})
  call dein#load_toml(s:filetype_toml, #{lazy: v:false})
  call dein#end()
  call dein#save_state()
endif

set secure
