[[plugins]]
repo = 'Shougo/dein.vim'

#[[plugins]]
#repo = 'junegunn/vim-plug'

# define your own operator
[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'ujihisa/neco-look'

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = 'vim-operator-user'
on_map = {nx = '<Plug>'}

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'
depends = 'vim-textobj-user'
on_map = {ox = '<Plug>'}

[[plugins]]
repo = 'pocke/vim-textobj-markdown'
depends = 'kana/vim-textobj-user'
on_map = [['xo', 'ac'], ['xo', 'ic']]

[[plugins]]
repo = 'jasonlong/vim-textobj-css'
depends = 'vim-textobj-user'

[[plugins]]
repo = 'kana/vim-textobj-entire'

[[plugins]]
repo = 'kana/vim-textobj-function'

[[plugins]]
repo = 'kana/vim-textobj-line'

[[plugins]]
repo = 'kana/vim-textobj-syntax'

[[plugins]]
repo = 'mattn/vim-textobj-url'

[[plugins]]
repo = 'haya14busa/vim-textobj-number'

[[plugins]]
repo = 'rhysd/vim-textobj-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'roxma/nvim-yarp'
on_if = "!has('nvim')"

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = "!has('nvim')"

[[plugins]]
repo = 'w0rp/ale'
hook_add = 'source ~/.vim/init/plugins/ale.vim'

[[plugins]]
repo = 'tpope/vim-speeddating'
on_cmd = 'SpeedDatingFormat'

[[plugins]]
repo = 'jceb/vim-orgmode'
depends = 'tpope/vim-speeddating'

[[plugins]]
repo = 'luochen1990/rainbow'
on_cmd = 'RainbowToggle'
hook_source = '''
source ~/.vim/init/plugins/ale.vim
let g:rainbow_active = 1
'''

