[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline_theme = 'light'
let g:airline_powerline_fonts = has('gui_running') ? 1 : 0
let g:ariline#extensions#tabline#enabled = 1 " enable the extension
let g:ariline#extensions#taboo#enabled = 1 " enable the extension
'''

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'fmoralesc/molokayo'
depends = 'molokai'
hook_add = 'colorscheme molokayo'

[[plugins]]
repo = 'plan9-for-vimspace/acme-colors'

[[plugins]]
repo = 'mitsuse/bombay.vim'

[[plugins]]
repo = 'endel/vim-github-colorscheme'

[[plugins]]
repo = 'marcopaganini/termschool-vim-theme'

[[plugins]]
repo = 'ravelll/vim-murk'

[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_source = '''
let g:solarized_termtrans = 1
let g:solarized_termcolors = 256
let g:solarized_contrast = "high"
let g:solarized_visibility = "high"
'''

[[plugins]]
repo = 'whatyouhide/vim-gotham'

[[plugins]]
repo = 'chriskempson/base16-vim'
hook_source = 'let base16colorspace = 256'
#hook_add = 'colorscheme base16-default-dark'

[[plugins]]
repo = 'morhetz/gruvbox'
