[[plugins]]
repo = 'Shirk/vim-gas'
on_ft = 'gas'

[[plugins]]
repo = 'syngan/vim-vimlint'
depends = 'ynkdir/vim-vimlparser'

[[plugins]]
repo = 'tpope/vim-endwise'
on_i = 1

[[plugins]]
repo = 'vim-scripts/gtk-vim-syntax'
on_ft = 'c'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = 'javascript'

[[plugins]]
repo = 'ternjs/tern_for_vim'
on_cmd = ['TernDef', 'TernDoc', 'TernType', 'TernRefs', 'TernRename']
on_ft = 'javascript'

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'othree/jspc.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'moll/vim-node'
on_ft = 'javascript'

[[plugins]]
repo = 'keith/swift.vim'
on_ft = 'swift'

[[plugins]]
repo = 't9md/vim-ruby-xmpfilter'
on_ft = 'ruby'

[[plugins]]
repo = 'derekwyatt/vim-scala'
on_ft = 'scala'

[[plugins]]
repo = 'vim-erlang/vim-erlang-runtime'
on_ft = 'erlang'

[[plugins]]
repo = 'dart-lang/dart-vim-plugin'
on_ft = 'dart'

[[plugins]]
repo = 'rhysd/vim-llvm'
on_ft = 'llvm'

[[plugins]]
repo = 'mitsuse/autocomplete-swift'
on_ft = 'swift'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'rhysd/vim-wasm'
on_ft = 'wast'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'mhartington/nvim-typescript'
on_if = "has('nvim')"
on_ft = 'typescript'

[[plugins]]
repo = 'eagletmt/neco-ghc'
on_ft = 'haskell'
external_commands = 'ghc-mod'

[[plugins]]
repo = 'aharisu/vim-gdev'
on_ft = 'scheme'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
let g:go_bin_path = expand('~/.go/bin')
let g:go_disable_autoinstall = 0

let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_fmt_command = "goimports"
let g:go_fmt_fail_silently = 1
let g:go_get_update = 0 " Disable updating dependencies
let g:go_snippet_engine = 'neosnippet'
'''

[[plugins]]
repo = 'nsf/gocode'
rtp = 'vim'
on_ft = 'go'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_source = 'let g:rustfmt_autosave = 1'

[[plugins]]
repo = 'racer-rust/vim-racer'
on_ft = 'rust'

[[plugins]]
repo = 'rhysd/rust-doc.vim'
on_ft = 'rust'

[[plugins]]
repo = 'Jagua/vim-denite-ghq'
on_source = 'denite.nvim'

[[plugins]]
repo = 'rhysd/vim-gfm-syntax'
on_event = 'BufRead'

[[plugins]]
repo = 'machakann/vim-vimhelplint'
on_ft = 'help'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
on_i = 1

[[plugins]]
repo = 'chrisbra/vim-zsh'
on_ft = 'zsh'

[[plugins]]
repo = 'zchee/deoplete-zsh'
on_ft = 'zsh'

[[plugins]]
repo = 'Shougo/deoplete-clangx'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_i = 1
on_ft = 'go'
hook_source = '''
let g:deoplete#sources#go#gocode_binary = $GOPATH.'/bin/gocode'
let g:deoplete#sources#go#use_cache = 1
'''

[[plugins]]
repo = 'kana/vim-filetype-haskell'
on_ft = 'haskell'

[[plugins]]
repo = 'itchyny/vim-haskell-indent'
on_ft = 'haskell'

[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = 'kotlin'

[[plugins]]
repo = 'shawncplus/phpcomplete.vim'
on_ft = 'php'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'JesseKPhillips/d.vim'
on_ft = 'd'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]]
repo = 'vim-jp/vim-cpp'
on_ft = 'cpp'

[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'
on_ft = 'cpp'

#[[plugins]]
#repo = 'justmao945/vim-clang'
#on_ft = ['c', 'cpp', 'objc']

[[plugins]]
repo = 'cjxgm/vimlight'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'rhysd/vim-crystal'
on_ft = 'crystal'

[[plugins]]
repo = 'chrisbra/csv.vim'
on_ft = 'csv'

[[plugins]]
repo = 'vim-erlang/vim-erlang-omnicomplete'
on_ft = 'erlang'

[[plugins]]
repo = 'elixir-lang/vim-elixir'
on_ft = 'elixir'

[[plugins]]
repo = 'awetzel/elixir.nvim'
depends = 'vim-elixir'
disabled = '!has("nvim")'
on_ft = 'elixir'

[[plugins]]
repo = 'pilu/vimux-elixir'
depends = 'benmills/vimux'
on_ft = 'elixir'

[[plugins]]
repo = 'dag/vim-fish'
on_ft = 'fish'

[[plugins]]
repo = 'raichoo/haskell-vim'
on_ft = 'haskell'

[[plugins]]
repo = 'vim-jp/vim-java'
on_ft = 'java'

[[plugins]]
repo = 'artur-shaik/vim-javacomplete2'
on_ft = 'java'

[[plugins]]
repo = 'google/vim-jsonnet'
on_ft = 'jsonnet'

[[plugins]]
repo = 'lfex/vim-lfe'
on_ft = 'lfe'

[[plugins]]
repo = 'tbastos/vim-lua'
on_ft = 'lua'

[[plugins]]
repo = 'WolfgangMehner/lua-support'
on_ft = 'lua'

[[plugins]]
repo = 'zah/nimrod.vim'
on_ft = 'nim'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'

[[plugins]]
repo = 'python-mode/python-mode'
on_ft = 'python'
hook_add = '''
let g:pymode_python = 'python3'
'''

[[plugins]]
repo = 'tpope/vim-rbenv'
on_ft = 'ruby'

[[plugins]]
repo = 'todesking/ruby_hl_lvar.vim'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-bundler'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-rails'
on_cmd = 'Rails'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-rake'
on_cmd = 'Rake'
on_ft = 'ruby'

[[plugins]]
repo = 'osyo-manga/vim-monster'
on_ft = 'ruby'
hook_add = 'let g:monster#completion#rcodetools#backend = "async_rct_complete"'

#[[plugins]]
#repo = 'uplus/deoplete-solargraph'

[[plugins]]
repo = 'chrisbra/vim-sh-indent'
on_ft = 'sh'

[[plugins]]
repo = 'clojure-vim/async-clj-highlight'
on_ft = 'clojure'

[[plugins]]
repo = 'clojure-vim/async-clj-omni'
on_ft = 'clojure'

