if &compatible
  set nocompatible
endif

call init#init('basic')
call init#init('enc')
call init#init('filetype')
call init#init('unix')
call init#init('view')
call init#init('dein')

if has('vim_starting') && !empty(argv())
  call init#on_filetype()
endif

if !has('vim_starting')
  call dein#call_hook('source')
  call dein#call_hook('post_source')

  syntax enable
  filetype plugin indent on
endif

call init#init('edit')
