if &compatible
  set nocompatible
endif

let $INIT_PATH = resolve(expand('<sfile>:p:h')) . '/'
function! s:init(path) abort
  let abspath = resolve($INIT_PATH . a:path . '.vim')
  execute 'source' fnameescape(abspath)
endfunction

augroup init_auto_cmd
  autocmd!
  autocmd FileType,Syntax,BufNewFile,BufNew,BufRead *?
        \ call init#on_filetype()
  autocmd CursorHold *.toml syntax sync minlines=300
augroup END
augroup filetypedetect
augroup END

call s:init('init-core')
call s:init('init-view')
call s:init('init-plugin')
call s:init('init-filetype')
call s:init('init-unix')
call s:init('init-edit')

if has('vim_starting') && !empty(argv())
  call init#on_filetype()
endif

if !has('vim_starting')
  call dein#call_hook('source')
  call dein#call_hook('post_source')
endif

set secure
